# Site settings
title:          Toronto Blog
description:    "The blog of my exchange semester in Toronto"
url:            "https://arvedluetzen.github.io/TorontoBlog/"

# Author
author:
  name:         Arved Luetzen
  email:        arvedluetzen@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale